### ISSUE TITLE
Finish code cleanup and commenting 

### ISSUE THREAD

**Issue by ash-j-f** [AIE-2017-Yr1-Group1/cultist-game#114]
Due by Wednesday!

**Comment by c4cookie** [comment]
following scripts I have edited/done coding review changes on
Cultist.cs
PlayerAnimation.cs
projectile.cs
imp.cs
impAnimations.cs
audiocontroller.cs
player.cs
cultistanimation.cs

**Comment by ash-j-f** [comment]
I've done a pass over ever *.cs file in the Scripts dir.

**Comment by ash-j-f** [comment]
Done in 8c0fe617ca440a9d6323ceb88694b40568dc318d
