### ISSUE TITLE
Difficulty system not working in editor, when accessed via main menu

### ISSUE THREAD

**Issue by ash-j-f** [AIE-2017-Yr1-Group1/cultist-game#157]
The difficulty system gives errors and won't display current difficulty in in-game menu, even when accessed via Main menu.

I'm editing the barrier and exit system so this should be looked at in the morning.

**Comment by ASharpy** [comment]
the main menu wont show current difficulty until were ready to build, what errors are u getting cause im on gold V3 and have no issues

**Comment by ash-j-f** [comment]
Only saw it in latest version of Gold V3. Giving error on scene start:
```
NullReferenceException: Object reference not set to an instance of an object
Conf.Awake () (at Assets/Scripts/Conf.cs:523)
```
But then difficulty wouldn't work even after returning to main menu.

It'll probably work in the final scene, just made the note so we are sure to check again.

I didn't try it as a built EXE.

**Comment by ash-j-f** [comment]
The error was breaking cam rotation as it causes Conf setup to fail on game start. So I added the following extra check for "&& Difficulty.instance != null" in Conf:
```

        /****************************************
        * Difficulties
        ****************************************/
        if (Application.isPlaying && Difficulty.instance != null)
        {
            switch (Difficulty.instance.Diftype)
            {
                case Difficulty.DifficultySettings.EASY:
                    imp.MaxHealth += imp.MaxHealth / 10
```

**Comment by ash-j-f** [comment]
This code had to be removed to make difficulty work in EXE and player mode
```
&& Difficulty.instance != null
```
But now we're back to the game being broken in Unity player mode as the Conf script doesn't finish initialising. So this system needs revamping.

**Comment by ash-j-f** [comment]
This section in InGameMenu.cs is also having similar issues and should be converted to use whatever new system
```
        //If the escape button is pressed and the game isnt paused, set time scale to 0 and display the menu
        if (Input.GetKeyDown(KeyCode.Escape) && !ispaused)
        {
            // Gets what difficulty the game is currently on and displays the appropriate string
            DiffText.text = Difficulty.instance.difficultyString;
```

**Comment by ash-j-f** [comment]
Difficulty system now resets difficulty to Easy on application start, and stores the difficulty setting during gameplay using the Unity Player Preferences system https://docs.unity3d.com/ScriptReference/PlayerPrefs.html
