### ISSUE TITLE
Player Script should register the player object with Configuration Manager automatically

### ISSUE THREAD

**Issue by ash-j-f** [AIE-2017-Yr1-Group1/cultist-game#3]
Player script to register the player object with Configuration Manager automatically. This will replace the manual assignment of player object we currently have to do in Conf manager.

**Comment by ash-j-f** [comment]
Mentioned this on the Hacknplan task https://app.hacknplan.com/p/39850/board?categoryId=1&milestoneId=88124&taskId=62&tabId=3

**Comment by ash-j-f** [comment]
Finding the current player is probably used by more than just camera. So maybe move the Player reference in Conf to its own section, not under Camera.

**Comment by c4cookie** [comment]
I am wonderful. this task shall be over
